
image: ubuntu:18.04

before_script:
  - apt-get update -qy
  - apt-get install -y lftp

build:
  script:
    #  - echo $CO_IP
    #  - echo $CO_USER
    #  - echo $CO_PASS
    - lftp -e 'set sftp:auto-confirm yes;set ssl:verify-certificate no;set sftp:connect-program "ssh -a -x -i $CO_KEY";mirror -X .* -X .*/ --reverse --verbose --delete . ~/; quit' -u $CO_USER,$CO_PASS sftp://$CO_IP -p 22

